# TESTE DE ROTA DA API
GET http://localhost:5000/api

### CRIACAO DE USUARIO
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "name": "João Silva",
    "email": "joao@email.com",
    "password": "gabrielbento"
}

### LOGIN DE USUARIO
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "joao@email.com",
    "password": "gabrielbento"
}

### MEU PERFIL
GET http://localhost:5000/user/me
Authorization: bearer 

### ATUALIZAR PERFIL
PATCH  http://localhost:5000/user/me
Authorization: bearer 
Content-Type: application/json

{
    "name": "João Silva II"
}

### TODOS USUARIOS - ADMIN
GET http://localhost:5000/user
Authorization: bearer 

### USUARIO BY ID - ADMIN
GET http://localhost:5000/user/1008f98f-ed5b-43dd-a806-818ab2058773
Authorization: bearer 

### DELETE BY ID - ADMIN
DELETE  http://localhost:5000/user/23c1f719-2baa-40d8-a104-deadf160253c
Authorization: bearer 