###
@token = {{login.response.body.token}}
@categoryId = {{category.response.body.$.[0].id}}

### Login
# @name login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "123456"
}


### Criar Categoria (ADMIN)
POST http://localhost:5000/category
Content-Type: application/json
Authorization: bearer {{token}}

{
  "name": "Roupa"
}



### Todas as Categorias
# @name category
GET http://localhost:5000/category
Authorization: bearer {{token}}


### Buscar Categoria por ID
GET http://localhost:5000/category/{{categoryId}}
Authorization: bearer {{token}}


### Atualizar Categoria (ADMIN)
PUT http://localhost:5000/category/{{categoryId}}
Content-Type: application/json
Authorization: bearer {{token}}

{
  "name": "Documentos Importantes"
}


### Deletar Categoria (ADMIN)
DELETE http://localhost:5000/category/{{categoryId}}
Authorization: bearer {{token}}
