###
@token = {{login.response.body.token}}
@categoryId = {{category.response.body.$.[0].id}}
@itemId = {{item.response.body.id}}


### Login (pegar token)
# @name login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "123456"
}

### Todas as Categorias
# @name category
GET http://localhost:5000/category
Authorization: bearer {{token}}



### Criar Item (USER ou ADMIN)
# @name item
POST http://localhost:5000/item
Content-Type: application/json
Authorization: bearer {{token}}

{
  "title": "Mochila preta",
  "description": "Mochila Adidas encontrada no pátio",
  "categoryId": "{{categoryId}}",
  "location": "Pátio central",
  "occurrenceDate": "2026-07-06T12:00:00.000Z",
  "type": "LOST"
}


### Listar todos os itens
GET http://localhost:5000/item
Authorization: bearer {{token}}


### Buscar item por ID
GET http://localhost:5000/item/{{itemId}}
Authorization: bearer {{token}}


### Atualizar item (USER dono ou ADMIN)
PATCH http://localhost:5000/item/{{itemId}}
Content-Type: application/json
Authorization: bearer {{token}}

{
  "title": "Mochila preta atualizada",
  "description": "Descrição atualizada do item"
}


### Marcar como resolvido
PATCH http://localhost:5000/item/{{itemId}}/resolve
Authorization: bearer {{token}}


### Deletar item (ADMIN)
DELETE http://localhost:5000/item/{{itemId}}
Authorization: bearer {{token}}