###
@token = {{login.response.body.token}}
@id = {{login.response.body.user.id}}

### TESTE DE ROTA DA API
GET http://localhost:5000/api

### CRIAÇÃO DE USUÁRIO
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "name": "João Silva",
    "email": "joao@email.com",
    "password": "gabrielbento",
    "phone": "(82) 99999-9999",
    "registration": "2023001234",
    "course": "Ciência da Computação",
    "institution": "IFAL"
}

### LOGIN
# @name login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "joao@email.com",
    "password": "gabrielbento"
}

### MEU PERFIL
GET http://localhost:5000/user/me
Authorization: Bearer {{token}}

### ATUALIZAR PERFIL
PATCH http://localhost:5000/user/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "João da Silva",
    "phone": "(82) 98888-8888",
    "course": "Sistemas de Informação",
    "institution": "UFAL"
}

### SOLICITAR RECUPERAÇÃO DE SENHA
POST http://localhost:5000/auth/forgot-password
Content-Type: application/json

{
    "email": "joao@email.com"
}

### RESETAR SENHA
POST http://localhost:5000/auth/reset-password
Content-Type: application/json

{
    "token": "ca094194a1aed98ad19617dd36623c7126b2d91e9b4231f76ee2d65dfd144aeb",
    "password": "12345"
}

### MUDAR SENHA
PATCH http://localhost:5000/auth/change-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "currentPassword": "gabrielbento",
    "newPassword":"123456"
}

### TODOS OS USUÁRIOS (ADMIN)
GET http://localhost:5000/user
Authorization: Bearer {{token}}

### USUÁRIO POR ID (ADMIN)
GET http://localhost:5000/user/{{id}}
Authorization: Bearer {{token}}

### EXCLUIR USUÁRIO (ADMIN)
DELETE http://localhost:5000/user/{{id}}
Authorization: Bearer {{token}}